default_install_hook_types:
  - pre-commit
  - commit-msg

repos:
  - repo: local
    hooks:
      - id: astro
        name: Astro check
        entry: pnpm astro check
        language: system
        pass_filenames: false
        files: \.(ts|astro)$
        stages: [pre-commit]

      - id: prettier
        name: Prettier
        entry: pnpm exec prettier --check src
        language: system
        pass_filenames: false
        files: \.(ts|tsx|js|jsx|json|css|md)$
        stages: [pre-commit]

  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v4.3.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
        args: [--verbose]
